#!/bin/bash
export VIRTUALENV_DIRECTORY='venv'

if [ ! -d "$VIRTUALENV_DIRECTORY" ]; then
    virtualenv $VIRTUALENV_DIRECTORY &&
    source $VIRTUALENV_DIRECTORY/bin/activate &&
    pip install pylint ipdb
else
	echo "[ERROR] Directory $VIRTUALENV_DIRECTORY already exists!"
fi

